<?xml version="1.0" encoding="UTF-8"?>

<project name="Chat" default="help">

  <property name="dir" value="${project.basedir}"/>

  <target name="help" description="lists available targets">
    <exec executable="phing" outputProperty="help">
      <arg line="-l"/>
    </exec>
    <echo>${help}</echo>
  </target>

  <target name="sniff" description="checks adherence to coding standards">
    <exec executable="phpcs" passthru="true" checkreturn="true">
      <arg line="--standard=PSR12 --runtime-set ignore_warnings_on_exit true classes tests admin.php index.php"/>
    </exec>
    <exec executable="phpcs" passthru="true" checkreturn="true">
      <arg line="--standard=PSR12 --runtime-set ignore_warnings_on_exit true --exclude=Generic.Files.LineLength config languages"/>
    </exec>
  </target>

  <target name="stan" description="runs static analyzer">
    <exec executable="phpstan" passthru="true" checkreturn="true"/>
  </target>

  <target name="test" description="runs all developer tests">
    <exec executable="phpunit" passthru="true" checkreturn="true"/>
  </target>

  <target name="js" description="formats and checks JavaScript">
    <exec executable="prettier" passthru="true" checkreturn="true">
      <arg line="--write --print-width 100 --tab-width 4 --trailing-comma es5 chat.js"/>
    </exec>
    <exec executable="jshint" passthru="true" checkreturn="true">
      <arg line="chat.js"/>
    </exec>
    <exec executable="tsc" passthru="true" checkreturn="true"/>
  </target>

  <target name="check" description="runs all checks" depends="sniff,stan,test,js"/>

  <target name="coverage" description="generates coverage report">
    <exec executable="phpunit" passthru="true" checkreturn="true">
      <arg value="--coverage-html"/>
      <arg file="coverage"/>
    </exec>
  </target>

  <target name="minify" description="minifies JS">
    <exec executable="uglifyjs" checkreturn="true" dir="${dir}">
      <arg line="chat.js --module --compress --mangle --output chat.min.js"/>
    </exec>
  </target>

   <target name="gen-help" description="builds help.htm from README.md">
    <exec executable="pandoc" passthru="true" checkreturn="true">
      <arg line="-s --eol=lf --template=help/template.htm -Vlang=en -Vpagetitle=&quot;User Manual&quot; -o help/help.htm README.md -t html"/>
    </exec>
    <exec executable="pandoc" passthru="true" checkreturn="true">
      <arg line="-s --eol=lf --template=help/template.htm -Vlang=de -Vpagetitle=&quot;Benutzerhandbuch&quot; -o help/help_de.htm README_de.md -t html"/>
    </exec>
  </target>

  <target name="build" description="builds a distributable ZIP archive">
    <exec executable="git" checkreturn="true">
      <arg line="archive -o export.tar HEAD"/>
    </exec>
    <untar file="export.tar" todir="export"/>
    <delete file="export.tar"/>
    <phingcall target="minify">
      <property name="dir" value="export/"/>
    </phingcall>
    <move todir="dist">
      <fileset dir="export">
        <include name="views/*.php"/>
      </fileset>
      <filterchain>
        <replaceregexp>
          <regexp pattern="&lt;\?(?!=|php)" replace="&lt;?php "/>
        </replaceregexp>
      </filterchain>
    </move>
    <move todir="dist">
      <fileset dir="export">
        <exclude name=".github/**"/>
        <exclude name=".phive/**"/>
        <exclude name="help/template.htm"/>
        <exclude name="tests/**"/>
        <exclude name="README*.md"/>
        <exclude name="build.xml"/>
        <exclude name="composer.*"/>
        <exclude name="phpstan.*"/>
        <exclude name="phpunit.xml"/>
        <exclude name="teplad.xml"/>
      </fileset>
    </move>
    <delete dir="export"/>
    <copy file="dist/config/config.php" tofile="dist/config/defaultconfig.php"/>
    <copy file="dist/languages/en.php" tofile="dist/languages/default.php"/>
    <zip destfile="Chat_XH-2.1-dev.zip" basedir="dist" prefix="chat/"/>
    <delete dir="dist"/>
  </target>

  <target name="build-patch" description="builds a distributable update package">
    <fail unless="patchee" message="patchee is not defined!"/>
    <unzip file="Chart_XH-2.1-dev.zip" todir="current"/>
    <unzip file="${patchee}" todir="patchee"/>
    <copy todir="dist">
      <fileset dir="current">
        <different targetdir="patchee" ignoreFileTimes="true"/>
      </fileset>
    </copy>
    <delete>
      <fileset dir="dist/chart">
        <include name="config/config.php"/>
        <include name="languages/??.php"/>
      </fileset>
    </delete>
    <if>
      <available file="dist/chart/css/stylesheet.css"/>
      <then>
        <move file="dist/chart/css/stylesheet.css" tofile="dist/chart/css/stylesheet-2.1-dev.css"/>
      </then>
    </if>
    <zip destfile="Chart_XH-2.1-dev-update-from-2.x.zip" basedir="dist" includeemptydirs="false"/>
    <delete dir="patchee" quiet="true"/>
    <delete dir="current" quiet="true"/>
    <delete dir="dist" quiet="true"/>
  </target>

</project>
